apiVersion: v1
kind: Service
metadata:
  name: swiggy
  namespace: swiggy-clone
  labels:
    app: swiggy
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: swiggy